# Generated by Django 4.1.6 on 2023-02-08 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=250)),
                ('categoria', models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta')], default='', max_length=12)),
                ('data_fotografia', models.DateTimeField(default=datetime.datetime.now)),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d')),
            ],
        ),
    ]
