# Generated by Django 4.1.6 on 2023-02-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografias',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
